//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsAppApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatsAppApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Afghanistan&quot;,93,412,1,&quot;AF&quot;,&quot;ps&quot;
        ///&quot;Albania&quot;,355,276,1,&quot;AL&quot;,&quot;sq&quot;
        ///&quot;Alberta&quot;,1403,302,720,&quot;CA&quot;,&quot;en&quot;
        ///&quot;Alberta&quot;,1780,302,720,&quot;CA&quot;,&quot;en&quot;
        ///&quot;Algeria&quot;,213,603,1,&quot;DZ&quot;,&quot;ar&quot;
        ///&quot;Andorra&quot;,376,213,3,&quot;AD&quot;,&quot;ca&quot;
        ///&quot;Angola&quot;,244,631,2,&quot;AO&quot;,&quot;pt&quot;
        ///&quot;Anguilla&quot;,1264,365,10,&quot;AI&quot;,&quot;en&quot;
        ///&quot;Antarctica (Australian bases)&quot;,6721,232,1,&quot;AQ&quot;,&quot;en&quot;
        ///&quot;Antigua and Barbuda&quot;,1268,344,50,&quot;AG&quot;,&quot;en&quot;
        ///&quot;Argentina&quot;,54,722,10,&quot;AR&quot;,&quot;es&quot;
        ///&quot;Armenia&quot;,374,283,10,&quot;AM&quot;,&quot;hy&quot;
        ///&quot;Aruba&quot;,297,363,1,&quot;AW&quot;,&quot;nl&quot;
        ///&quot;Ascension&quot;,247,658,1,&quot;AC&quot;,&quot;en&quot;
        ///&quot;Australia&quot;,61,505,1,&quot;AU&quot;,&quot;en&quot;
        ///&quot;Austria&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
    }
}
